### ISSUE TITLE
module issue on Kubuntu Bionic

### ISSUE THREAD

**Issue by My1** [conorpp/solo-desktop#1]
on npm start.

```
App threw an error during load
Error: Cannot find module '../Util'
Require stack:
- /home/my1/solo-desktop/app/bootloader.js
- /home/my1/solo-desktop/app/routes.js
- /home/my1/solo-desktop/app/main.js
- /home/my1/solo-desktop/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/my1/solo-desktop/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/my1/solo-desktop/app/bootloader.js:21:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
A JavaScript error occurred in the main process
```

**Comment by My1** [comment]
okay my solo hacker doesnt seem to be found.

clicking on refresh just results in

```
list
reply to  list
list
reply to  list
list
reply to  list
```

but I can do normal Fido actions, so udev is definitely set (unless this application needs extra rules)

**Comment by conorpp** [comment]
Can you update and try again?  I added some logs that might be able to help.

Or you can run `main/hid.js` directly with node to run it's tests.

**Comment by My1** [comment]
```
my1@my1-qb:~/solo-desktop$ node main/hid.js 
module.js:549
    throw err;
    ^

Error: Cannot find module './util'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/my1/solo-desktop/main/hid.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by My1** [comment]
btw more fun.

<details>
<summary>
Trying to build a release:
</summary>

~~~
my1@my1-qb:~/solo-desktop$ npm run release

> solo-desktop@1.0.0 release /home/my1/solo-desktop
> gulp release

[21:13:16] Using gulpfile ~/solo-desktop/gulpfile.js
[21:13:16] Starting 'release'...
[21:13:16] Starting 'build'...
[21:13:16] Starting 'copy'...
[21:13:16] Finished 'copy' after 38 ms
[21:13:16] Starting 'html'...
[21:13:16] Finished 'html' after 5.85 ms
[21:13:16] Starting 'css'...
[21:13:18] Finished 'css' after 1.57 s
[21:13:18] Starting 'js'...
[21:13:26] Finished 'js' after 7.94 s
[21:13:26] Finished 'build' after 9.56 s
[21:13:26] Starting '<anonymous>'...
  • electron-builder  version=21.2.0 os=4.15.0-1059-oem
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • rebuilding native dependencies  dependencies=node-hid@0.7.9, usb@1.6.0 platform=linux arch=x64
  • install prebuilt binary  name=node-hid version=0.7.9 platform=linux arch=x64
  • install prebuilt binary  name=usb version=1.6.0 platform=linux arch=x64
  • build native dependency from sources  name=usb
                                          version=1.6.0
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.2
    prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /home/my1/.npm/_prebuilds/193821-usb-v1.6.0-electron-v73-linux-x64.tar.gz
    prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v73-linux-x64.tar.gz
    prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v73-linux-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=6.1.2 runtime=electron arch=x64 libc= platform=linux)
    
  • build native dependency from sources  name=node-hid                                                                                                                                                                          
                                          version=0.7.9                                                                                                                                                                          
                                          platform=linux                                                                                                                                                                         
                                          arch=x64                                                                                                                                                                               
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)                                                                                
                                          error=prebuild-install info begin Prebuild-install version 5.3.2                                                                                                                       
    prebuild-install WARN install prebuilt binaries enforced with --force!                                                                                                                                                       
    prebuild-install WARN install prebuilt binaries may be out of date!                                                                                                                                                          
    prebuild-install info looking for cached prebuild @ /home/my1/.npm/_prebuilds/edced7-node-hid-v0.7.9-electron-v73-linux-x64.tar.gz                                                                                           
    prebuild-install http request GET https://github.com/node-hid/node-hid/releases/download/v0.7.9/node-hid-v0.7.9-electron-v73-linux-x64.tar.gz                                                                                
    prebuild-install http 404 https://github.com/node-hid/node-hid/releases/download/v0.7.9/node-hid-v0.7.9-electron-v73-linux-x64.tar.gz                                                                                        
    prebuild-install WARN install No prebuilt binaries found (target=6.1.2 runtime=electron arch=x64 libc= platform=linux)
    
  • packaging       platform=linux arch=x64 electron=6.1.2 appOutDir=dist/linux-unpacked
  • building        target=snap arch=x64 file=dist/solo-desktop_1.0.0_amd64.snap
  • building        target=AppImage arch=x64 file=dist/solo-desktop-1.0.0.AppImage
  • cannot map macOS category to Linux. If possible mapping is known for you, please file issue to add it.  macCategory=solokeys.desktop.utility.application
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • default Electron icon is used  reason=application icon is not set
  • cannot map macOS category to Linux. If possible mapping is known for you, please file issue to add it.  macCategory=solokeys.desktop.utility.application
  • application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z size=1.5 MB parts=1
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=3.079s
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z duration=3.099s
  • publishing      publisher=Snap Store
  • uploading       file=solo-desktop_1.0.0_amd64.snap provider=snapStore
  ⨯ snapcraft is not installed, please: sudo snap install snapcraft --classic  
  ⨯ /home/my1/solo-desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                      Error: /home/my1/solo-desktop/node_modules/app-builder-bin/linux/x64/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                          at ChildProcess.childProcess.once.code (/home/my1/solo-desktop/node_modules/builder-util/src/util.ts:239:14)
                                                                                                                                          at Object.onceWrapper (events.js:317:30)
                                                                                                                                          at emitTwo (events.js:126:13)
                                                                                                                                          at ChildProcess.emit (events.js:214:7)
                                                                                                                                          at maybeClose (internal/child_process.js:925:16)
                                                                                                                                          at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[21:14:31] '<anonymous>' errored after 1.08 min
[21:14:31] Error: exited with error code: 1
    at ChildProcess.onexit (/home/my1/solo-desktop/node_modules/end-of-stream/index.js:40:36)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[21:14:31] 'release' errored after 1.23 min

npm ERR! Linux 4.15.0-1059-oem
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "release"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! solo-desktop@1.0.0 release: `gulp release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solo-desktop@1.0.0 release script 'gulp release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the solo-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs solo-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls solo-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/my1/solo-desktop/npm-debug.log
~~~

</details>

[npm-debug.log](https://github.com/solokeys/solo-desktop/files/3802079/npm-debug.log)
